# Generated by Django 3.2.7 on 2021-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=60)),
                ('telefono', models.IntegerField(max_length=20)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
