# Generated by Django 3.2.7 on 2021-09-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
