# Generated by Django 3.2.7 on 2021-09-09 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Padres', '0002_padres_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2021, 9, 9, 21, 48, 40, 234144))),
                ('cantidad', models.FloatField(default=0.0)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Padres.padres')),
            ],
        ),
    ]
