# Generated by Django 3.2.7 on 2021-09-17 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 11, 26, 38, 995157)),
        ),
    ]
