# Generated by Django 3.2.7 on 2021-09-17 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0003_alter_pagos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
