# Generated by Django 3.2.7 on 2021-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0004_alter_pagos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='numeroFactura',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
