# Generated by Django 3.2.7 on 2021-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_pagos_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='numeroFactura',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
