# Generated by Django 3.2.7 on 2021-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0006_alter_pagos_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='numeroFactura',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
