# Generated by Django 3.2.7 on 2021-09-20 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0011_alter_pagos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 9, 26, 53, 165043, tzinfo=utc)),
        ),
    ]
