# Generated by Django 3.2.7 on 2021-09-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Padres', '0001_initial'),
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Padres.padres'),
        ),
    ]
