# Generated by Django 3.2.7 on 2021-09-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0001_initial'),
        ('Alumnos', '0002_alumnos_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.CharField(choices=[('1P', '1 Primaria'), ('2P', '2 Primaria'), ('3P', '3 Primaria'), ('4P', '4 Primaria'), ('5P', '5 Primaria'), ('6P', '6 Primaria'), ('1E', '1 ESO'), ('2E', '2 ESO'), ('3E', '3 ESO'), ('4E', '4 ESO'), ('1B', '1 Bachillerato'), ('2B', '2 Bachillerato'), ('OT', 'Otro')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profesores.profesores'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='telefono',
            field=models.CharField(default='', max_length=100),
        ),
    ]
