# Generated by Django 3.2.7 on 2021-09-17 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_auto_20210908_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='fechaInscripcion',
            field=models.DateField(default=datetime.date(2021, 9, 17)),
        ),
    ]
