# Generated by Django 3.2.7 on 2021-09-19 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_alumnos_fechainscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fechaInscripcion',
            field=models.DateField(default=datetime.date(2021, 9, 19)),
        ),
    ]
