# Generated by Django 3.2.7 on 2021-09-19 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_alter_alumnos_fechainscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fechaInscripcion',
            field=models.DateField(default=datetime.datetime(2021, 9, 19, 14, 36, 57, 225855, tzinfo=utc)),
        ),
    ]
